### ISSUE TITLE
Site feedback RJ 2024-04-24

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/website#12]
- [x] On the main page the 4th icon on the right side (computer with angle brackets) moves slightly down and to the right when hovered
- [x] Do we need the home icon on the top right, since the CL logo also takes you home?  If so, is it possible to make it a cottage? :)
- [x] The logos for partners should link to the partner sites.  I will provide links https://github.com/CottageLabs/website/issues/12#issuecomment-2075003453 
- [x] How is the trusted partners panel going to work, will it be a carousel?  There are some high profile clients I'd like to include.  I will provide a list (along with the links as per the above https://github.com/CottageLabs/website/issues/12#issuecomment-2075003453)
- [x] On the service description pages (e.g. OA Infrastructure) can we change the intro to Explore more to "Discover how we bring your projects to life"
- [x] On the service description pages can we remove the Related Technologies section, it doesn't quite fit there
- [x] For the OA.Works project, can we make sure it's just called oa-works in the URL bar, as it isn't called OA Button any more
- [x] On the front page (and maybe in other places) make sure Visualise is spelled the UK way rather than the US was (Visualize)
- [x] On the front page rename "Access Data Repositories" to just "Data Repositories"
- [x] The RUB logo is white so you can't see it against the background
- [x] The bespoke developments page requires example projects (I will provide: https://github.com/CottageLabs/website/issues/12#issuecomment-2075011065)
- [x] On the project and data lifecycle pages either remove the "see how we do it in our projects" or properly center it in the page, and change the label to "Our projects"
- [x] Remove the following search tags: Dv, OJS, Postgres, SWORD, Todo
- [x] Correct/merge the following tags:
    * `Samver` is a typo, should be `Samvera`, which will line it up with the other Samvera projects
    * `Elasticsearch` and `Search` to both be renamed `Search Technologies`
    * `Single Sign On` to be renamed `Security`, which will line it up with the other Security projects
 - [x] Logo on the "our project" page and service pages need to be clearer which projects they are for.  Perhaps the full name of the project could be under the logo, and the squares become rectangles? I will provide a list of the project names: https://github.com/CottageLabs/website/issues/12#issuecomment-2075141511
 - [ ] On the Our Projects page, change the header All Projects to Featured Projects
 - [x] Project pages should have titles with the title of the project (I will provide, as per above: https://github.com/CottageLabs/website/issues/12#issuecomment-2075141511)
 - [x] The "Go back to the project browser" button seems rather large and intrusive, is there a better more discrete but usable way to do this?  Perhaps a breadcrumb?
 - [x] Add screenshots for all the projects.  Discussed via slack already
     * sword: https://github.com/CottageLabs/website/issues/12#issuecomment-2075176775
     * city of culture: https://github.com/CottageLabs/website/issues/12#issuecomment-2075213375
 - [x] `Related Technologies` as a phrase on the various pages it is used isn't quite appropriate, as some aren't technologies.  I'm thinking of calling them "Themes", so could change this to `Related Themes`, `Related Project Themes` or just `Themes`?
 - [x] EUI invenio project shouldn't use the Invenio logo, that will create confusion when we talk more about Invenio as a platform.  See next point for proposal about how we do logos for projects that don't have logos:
 - [x] I have attempted to provide logos for all projects in the comments below. If a project doesn't have a clear logo, propose that we just make a square logo with the name of the project black text on transparent background, fitting into a square in the best way possible.  So, for example, for EUI, just `EUI` black on white.
 - [x] Project names should match the URL space (I will provide project names and proposed url paths: https://docs.google.com/spreadsheets/d/132IuLErde9ZuEYCnGk1SqIC5mwyzMXp498IWTtm-JC8/edit#gid=683188593)
 - [ ] WNA logo on project page is too low quality, check their website see if we can find a better one, or make this one smaller
 - [x] NGLP logo on project page is too low quality.  I don't think a better logo exists, so may just have to shrink this one
 - [x] SWORD does have an official logo: https://sword.cottagelabs.com/ (it's old and crap but recognisable)
 - [x] On the About Us page there is a "work with us link" on the right which goes to a 404.  Presume this is the jobs page, in which case I'd take it out of the About Us page and put it on the general footer, and put in a placeholder page saying "no openings at this time" (I will provide complete text)
 - [x] The partners names should have line breaks between the names, as on my screen Anusha's name is too long for the space but it's the only one that wraps.

**Comment by richard-jones** [comment]
Here is the list of clients, their names to use, and the logos to use: https://docs.google.com/spreadsheets/d/132IuLErde9ZuEYCnGk1SqIC5mwyzMXp498IWTtm-JC8/edit#gid=2120072672

**Comment by richard-jones** [comment]
Projects to include on the Bespoke Developments page:

These are the ones with an x in the column M in the projects sheet: https://docs.google.com/spreadsheets/d/132IuLErde9ZuEYCnGk1SqIC5mwyzMXp498IWTtm-JC8/edit#gid=1633634074

For completeness, these are:
* DOAJ
* EMLO
* Hull City of Culture
* JCT
* Materiom
* OA.Works
* JCS
* WNA

**Comment by richard-jones** [comment]
Project names, links and logos

https://docs.google.com/spreadsheets/d/132IuLErde9ZuEYCnGk1SqIC5mwyzMXp498IWTtm-JC8/edit#gid=683188593

If we could include the link to the project on the project page that would be great.

**Comment by richard-jones** [comment]
SWORD screenshots, I'm afraid they are not much to look at!

![Screenshot from 2024-04-24 15-55-29](https://github.com/CottageLabs/website/assets/856138/d7cb9b28-a414-4f2c-95b4-cab1acb876a7)
![Screenshot from 2024-04-24 15-56-04](https://github.com/CottageLabs/website/assets/856138/65e58305-f92a-41f2-ac79-a4495e28bc13)
![Screenshot from 2024-04-24 16-07-35](https://github.com/CottageLabs/website/assets/856138/fe799cd4-e7d1-4990-8e9b-0c10d755cdd4)

**Comment by richard-jones** [comment]
City of Culture screenshots

![Screenshot from 2024-04-24 16-09-38](https://github.com/CottageLabs/website/assets/856138/0360a0f4-b78d-4efe-83fc-1970de156ee4)
![Screenshot from 2024-04-24 16-09-08](https://github.com/CottageLabs/website/assets/856138/e82ae410-787d-49b7-acf8-b26101facb90)
![Screenshot from 2024-04-24 16-19-10](https://github.com/CottageLabs/website/assets/856138/641af19e-a577-42c7-8228-d40dbfd4e9c3)

**Comment by amdomanska** [comment]
@richard-jones a few comments to your feedback. I've copied your list for convenience, if I haven't added anything you may assume simple :+1: ;)

- [ ] On the main page the 4th icon on the right side (computer with angle brackets) moves slightly down and to the right when hovered
- [ ] Do we need the home icon on the top right, since the CL logo also takes you home?  If so, is it possible to make it a cottage? :)
_Yes, it's a good practice to add separate link for Home apart from the logo. It actually should be just text "home" to make it clear. Is that ok?_

- [ ] The logos for partners should link to the partner sites.  I will provide links https://github.com/CottageLabs/website/issues/12#issuecomment-2075003453 
- [ ] How is the trusted partners panel going to work, will it be a carousel?  There are some high profile clients I'd like to include.  I will provide a list (along with the links as per the above https://github.com/CottageLabs/website/issues/12#issuecomment-2075003453)
_Could you please tell me how long that list is going to be? I assumed (I shouldn't, that's a good point!) that it won't be more than 9-12, but if you could tell me how many to include I will figure that out :)_

- [ ] On the service description pages (e.g. OA Infrastructure) can we change the intro to Explore more to "Discover how we bring your projects to life"
- [ ] On the service description pages can we remove the Related Technologies section, it doesn't quite fit there
- [ ] For the OA.Works project, can we make sure it's just called oa-works in the URL bar, as it isn't called OA Button any more
- [ ] On the front page (and maybe in other places) make sure Visualise is spelled the UK way rather than the US was (Visualize)
- [ ] On the front page rename "Access Data Repositories" to just "Data Repositories"
- [ ] The RUB logo is white so you can't see it against the background
_I don't remember where I took that logo from but it is not possible to just change the version I've got. If you could provide the black version or the svg then I will replace it, otherwise I will just remove the logo and use the name of the project (in line with the requirement in one of the further points)_

- [ ] The bespoke developments page requires example projects (I will provide: https://github.com/CottageLabs/website/issues/12#issuecomment-2075011065)
- [ ] On the project and data lifecycle pages either remove the "see how we do it in our projects" or properly center it in the page, and change the label to "Our projects"
_It was supposed to be aligned with the text to the right. I understand this is not clear, point taken! ;)_

- [ ] Remove the following search tags: Dv, OJS, Postgres, SWORD, Todo
- [ ] Correct/merge the following tags:
    * `Samver` is a typo, should be `Samvera`, which will line it up with the other Samvera projects
    * `Elasticsearch` and `Search` to both be renamed `Search Technologies`
    * `Single Sign On` to be renamed `Security`, which will line it up with the other Security projects
 - [ ] Logo on the "our project" page and service pages need to be clearer which projects they are for.  Perhaps the full name of the project could be under the logo, and the squares become rectangles? I will provide a list of the project names: https://github.com/CottageLabs/website/issues/12#issuecomment-2075141511
 - [ ] On the Our Projects page, change the header All Projects to Featured Projects
 - [ ] Project pages should have titles with the title of the project (I will provide, as per above: https://github.com/CottageLabs/website/issues/12#issuecomment-2075141511)
 _Do you mean besides the logo and the description at the top?_
 
![image](https://github.com/CottageLabs/website/assets/8298769/735b53c4-c0cb-406a-b6d1-3ec9d9dbc0a0)

_Could we just make sure that the full project name is bold at the very beginning of that description?_

 - [ ] The "Go back to the project browser" button seems rather large and intrusive, is there a better more discrete but usable way to do this?  Perhaps a breadcrumb?
 _You're right, that's definitely is not the good place for the primary button! But a breadcrumb would be a little over the top here as we don't have complicated hierarchy (unless we introduce it everywhere on the site. I'll change it to something more subtle._
 
 - [ ] Add screenshots for all the projects.  Discussed via slack already
     * sword: https://github.com/CottageLabs/website/issues/12#issuecomment-2075176775
     * city of culture: https://github.com/CottageLabs/website/issues/12#issuecomment-2075213375
 - [ ] `Related Technologies` as a phrase on the various pages it is used isn't quite appropriate, as some aren't technologies.  I'm thinking of calling them "Themes", so could change this to `Related Themes`, `Related Project Themes` or just `Themes`?
 - [ ] EUI invenio project shouldn't use the Invenio logo, that will create confusion when we talk more about Invenio as a platform.  See next point for proposal about how we do logos for projects that don't have logos:
 - [ ] I have attempted to provide logos for all projects in the comments below. If a project doesn't have a clear logo, propose that we just make a square logo with the name of the project black text on transparent background, fitting into a square in the best way possible.  So, for example, for EUI, just `EUI` black on white.
 - [ ] Project names should match the URL space (I will provide project names and proposed url paths: https://docs.google.com/spreadsheets/d/132IuLErde9ZuEYCnGk1SqIC5mwyzMXp498IWTtm-JC8/edit#gid=683188593)
 - [ ] WNA logo on project page is too low quality, check their website see if we can find a better one, or make this one smaller
 - [ ] NGLP logo on project page is too low quality.  I don't think a better logo exists, so may just have to shrink this one
 - [ ] SWORD does have an official logo: https://sword.cottagelabs.com/ (it's old and crap but recognisable)
 _I have never meant these logos to be the final ones, more like a placements to show the idea ;)_
 
 - [ ] On the About Us page there is a "work with us link" on the right which goes to a 404.  Presume this is the jobs page, in which case I'd take it out of the About Us page and put it on the general footer, and put in a placeholder page saying "no openings at this time" (I will provide complete text)
 _Oops, oversight, sorry for that!_
 - [ ] The partners names should have line breaks between the names, as on my screen Anusha's name is too long for the space but it's the only one that wraps.
 _It was intended, I wouldn't consider that a problem (that only Anusha's name wraps) but also not a problem to change it so that all the names are in two lines._

**Comment by amdomanska** [comment]
- [ ] Rethink <h2> style Doesn't work great with longer text like `<h2>Discover how we bring your projects to life</h2>`

**Comment by amdomanska** [comment]
1.

> On the front page rename "Access Data Repositories" to just "Data Repositories"

My aim was to make sure that the link texts are "actionable" - therefore the verb at the beginning of each of them (Explore..., Visualise..., Craft...). Making link texts actionable is essential for enhancing user engagement and navigation on the website. When links contain actionable language, such as verbs or phrases prompting action, they provide clear direction to users on what to expect when they click. This clarity reduces ambiguity, improves the user experience, and increases the likelihood of users interacting with the content. We will lose this (and consistency) if we remove the word "Access...". Could you suggest some other verb that fits there better?

2. EMLO project is listed as Featured but has no searchable tags :slightly_smiling_face:

**Comment by richard-jones** [comment]
> Do we need the home icon on the top right, since the CL logo also takes you home? If so, is it possible to make it a cottage? :)
Yes, it's a good practice to add separate link for Home apart from the logo. It actually should be just text "home" to make it clear. Is that ok?
RJ: yes, sure

This became the text "Homepage", can we just use "Home" instead?

> The logos for partners should link to the partner sites. I will provide links https://github.com/CottageLabs/website/issues/12#issuecomment-2075003453

I think there was some confusion here.  I didn't mean the CL partners (my, Steve, Anusha), I meant the "Trusted Partners", i.e. the clients.  The link gives you a comment with the client name and their website

> On the Our Projects page, change the header All Projects to Featured Projects

To clarify, this is the header is "All Projects" just above the project logos, not the main title "Our Projects".  It is called "Featured Projects" everywhere else on the website

**Comment by Steven-Eardley** [comment]
Clipping on the project lifecycle diagram:

![image](https://github.com/CottageLabs/website/assets/1446355/698b5c39-8a78-4c75-80c9-f1975de3dc42)
